version: '3.9'

# Network for Laravel 10
networks:
  web_network:
    name: laravel10
    driver: bridge

services:

  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: laravel10_mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=laravel10db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
    ports:
      - "3660:3306"
    restart: always
    networks:
      - web_network

  # PHP App Service 
  app:
    depends_on:
      - db
    build: ./php
    image: laravel10-app
    container_name: laravel10_app
    restart: always
    volumes:
      - ./src:/var/www
    networks:
      - web_network

  # Nginx Web Server Service
  nginx:
    depends_on:
      - app
    image: nginx:1.19.8-alpine
    container_name: laravel10_nginx
    volumes:
      - ./src:/var/www
      - ./nginx/conf:/etc/nginx/conf.d
    ports:
      - "8880:80"
    restart: always
    networks:
      - web_network

  # phpMyAdmin (MySQL managment)
  phpmyadmin:
    image: phpmyadmin:5.1.0-apache
    depends_on:
      - db
    container_name: laravel10_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8890:80"
    restart: always
    networks:
      - web_network
